### ISSUE TITLE
pin code errror

### ISSUE THREAD

**Issue by hujianglang** [OneKeyHQ/OneKey-Wallet#1]
when i want to backup my onekey wallet, i read the instruction, most is ok, but 
because when i input pin code in onekey, i set 6 numbers ,but onekey must input 9 numbers. So  error error -- and then i input the pin code on Desktop , it's ok .

**Comment by rayston92** [comment]
Hi, you can press the ⬆️ ⬇️ button to switch the digit into ☑️ and then hit OKay.
We supoort from 1-9 digit PIN on device, of course 6-digit is supported.

**Comment by AmagiDDmxh** [comment]
Hi, @hujianglang 

Let us know if your problems been solved, also let us know if you want more helps.

If no further issue were happened, we are about to close this issue in one more day.
